name: revvdoutnode
services:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: https://github.com/RehanALiBalti/revvdoutnode.git
    name: revvdoutnode
